### ISSUE TITLE
[Bug] Cryostat preset layout templates are flagged as invalid

### ISSUE THREAD

**Issue by maxcao13** [cryostatio/cryostat-web#1005]
## Current Behavior:
After selecting a Memory Monitoring template and creating a new dashboard layout, some MBean cards seem to be considered invalid because of the themeColor.
![image](https://user-images.githubusercontent.com/69827283/235559821-7c243f32-c1c5-49cc-8470-316214d97c88.png)

**Comment by tthvo** [comment]
Seems like its problematic to have case-sensitive set everywhere. How about using lower-case for all and use lodash.capitalize function for display in the selector?
