### ISSUE TITLE
[Task] 2.3 user-facing string updates

### ISSUE THREAD

**Issue by maxcao13** [cryostatio/cryostat-web#1013]
2.3 user-facing string updates. This is only error/exception/warning messages for this release.

**Comment by tthvo** [comment]
Is https://github.com/cryostatio/cryostat-web/issues/589 part of this task?

**Comment by andrewazores** [comment]
It's talking about one particular instance that was pointed out to me previously, so I think the PR closing this issue may as well close out that one too.
