### ISSUE TITLE
[Bug] Inconsistent capitalization in in-app help menu

### ISSUE THREAD

**Issue by andrewazores** [cryostatio/cryostat-web#1146]
### Current Behavior

"Quick Starts" vs "Guided tour"

Which style should be preferred?

### Anything else?

![image](https://github.com/cryostatio/cryostat-web/assets/3787464/fc25b842-b72a-4b20-9084-fd1182b9df69)

**Comment by aali309** [comment]
@andrewazores ping

**Comment by tthvo** [comment]
This might help: https://www.patternfly.org/ux-writing/capitalization#red-hat-product-uis. Seems like `Quick Starts` and `Guided Tour` would be good choice.
