### ISSUE TITLE
[Bug] Topology "copy to clipboard" action fails

### ISSUE THREAD

**Issue by andrewazores** [cryostatio/cryostat-web#1167]
### Current Behavior

Clicking the "copy to clipboard" icon on the Topology > Create Custom Target view fails. An error appears in the console and the text is not copied into the system clipboard.

### Expected Behavior

There should be no error in the console and the text should be copied into the clipboard.

### Steps To Reproduce

1. Run Cryostat 2.5.0-snapshot
2. Go to Topology > Create Custom Target
3. Click the clipboard icon to copy the example JMX URL

### Environment

```Markdown
Cryostat 2.5.0

In Cryostat 2.4.0(-pre) this works as expected.
```

### Anything else?

![Screenshot_2023-11-28_14-07-20](https://github.com/cryostatio/cryostat-web/assets/3787464/b9189427-b028-4fe3-a5fe-d7cdca5b3efb)

**Comment by tthvo** [comment]
Sorry, I have been checking this out and seems to be working: directly with cryostat server and via `yarn start:dev`.

![image](https://github.com/cryostatio/cryostat-web/assets/68053619/e29c1f2a-69f0-4119-8a23-f0248c84fc16)

**Comment by tthvo** [comment]
Maybe, it is some browser restrictions that prevents clipboard from being available?

**Comment by andrewazores** [comment]
Hmm. Okay, I'll check again with another browser or with extensions disabled or something. Could just be on my end.

**Comment by andrewazores** [comment]
Hmm, I can't reproduce this anymore either. It probably was just something with my browser setup at the time.

**Comment by tthvo** [comment]
Ahh right I saw the same thing. I suppose this is the issue: https://stackoverflow.com/questions/51805395/navigator-clipboard-is-undefined

> This requires a secure origin — either HTTPS or localhost (or disabled by running Chrome with a flag). Just like for ServiceWorker, this state is indicated by the presence or absence of the property on the navigator object.

> https://developers.google.com/web/updates/2018/03/clipboardapi

> This is noted in the spec with [SecureContext] on the interface: https://w3c.github.io/clipboard-apis/#dom-navigator-clipboard

> You can check the state of window.isSecureContext to learn if that's the reason a feature is unavailable. [Secure contexts | MDN](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts)


When I tried with `http://localhost:8181`, it worked fine. However, `http://cryostat3:8181` failed as in the issue.

**Comment by tthvo** [comment]
For `cryostat3` hostname over HTTP:

![Screenshot from 2023-11-29 10-17-23](https://github.com/cryostatio/cryostat-web/assets/68053619/5874fd79-4f7f-4059-86c3-b406cd2c874c)


For `localhost` hostname over HTTP:

![image](https://github.com/cryostatio/cryostat-web/assets/68053619/f768378e-69a2-4fdd-9389-1dd9a47f134a)

**Comment by andrewazores** [comment]
Ahh, nice find, thanks!
