### ISSUE TITLE
[Bug] Custom Target is no longer deletable from topology view

### ISSUE THREAD

**Issue by tthvo** [cryostatio/cryostat-web#1251]
### Current Behavior

![image](https://github.com/cryostatio/cryostat-web/assets/68053619/6117d3a6-374e-4637-adf1-7fb0063d783c)

There are no delete button for custom targets.

### Expected Behavior

Custom Target should be deletable from topology view through quick action menu.

### Steps To Reproduce

- On latest cryostat3 `main` commit, run `bash smoketest.bash`.
- Login and go topology view.
- Click the top-left catalog icon on the toolbar and select create new custom target.
- Create a custom target with `localhost:9091`.
- Once the target is created, click on the three-dot icon on the JDK avatar (bottom-right) to see quick action menu.
- No delete option is shown.

### Environment

```Markdown
- OS: Fedora
- Environment: Local smoketest with `docker-compose`.
```

### Anything else?

The same behaviour when deploying on k8s.

**Comment by andrewazores** [comment]
Probably related to/same as https://github.com/cryostatio/cryostat3/issues/406

**Comment by tthvo** [comment]
Oh actually, I am seeing that the front-end expects the custom target to have `nodeType` to be `CustomTarget` according to its allowList:

https://github.com/cryostatio/cryostat-web/blob/2e0357d39fef152c3f8dab320c35e865b41a6032/src/app/Topology/Actions/utils.tsx#L114

Currently, for cryostat3, the custom target has nodeType `JVM`. Should it be `CustomTarget` instead like previously?

**Comment by andrewazores** [comment]
Ah, I see.

I think that's an OK fix in the short term, but longer term I would rather it use the JVM nodeType and have the front-end determine which nodes are deletable some other way. Maybe by checking the REALM annotation?

**Comment by tthvo** [comment]
> I think that's an OK fix in the short term, but longer term I would rather it use the JVM nodeType and have the front-end determine which nodes are deletable some other way. Maybe by checking the REALM annotation?

Yeah, check for REALM annotation sounds good to me! I can help see if there can be a quick change on the front-end...
