### ISSUE TITLE
[Bug] Topology view does not update on target notifications

### ISSUE THREAD

**Issue by andrewazores** [cryostatio/cryostat-web#1253]
Looks like it worked - the deletion button appears again, and after clicking it I can see a request sent and success response from the server, and a "target lost" notification. However, the Topology view didn't update on the notification, so I had to navigate away and back to see the updated view state.

Seems like a separate bug, but worth noting. In testing https://github.com/cryostatio/cryostat3/pull/407 it looks like Agents deregistering also doesn't trigger Topology to update, so it could be a common root cause.

_Originally posted by @andrewazores in https://github.com/cryostatio/cryostat-web/issues/1252#issuecomment-2076026769_

**Comment by tthvo** [comment]
Oh that's also odd. On my end, after seeing the loss notification (i.e. for custom target), the target disappeared. That also worked for kubeAPIDiscovery where I deleted a deployment or scale down replicas.

**Comment by andrewazores** [comment]
Worked this time around - I think I may have been running an image based on https://github.com/cryostatio/cryostat3/pull/407 when it happened, so this is really a bug in that PR, not one in `main`.

**Comment by andrewazores** [comment]
Here is my simple reproducer:

Run:
```bash
$ ./smoketest.bash -O
```

Then open the web UI and go to the Topology view. Create a custom target `localhost:9091`, then delete it. It should work as expected.

Then stop the smoketest and restart it, this time:
```bash
$ ./smoketest.bash -Ot # add the -t to run sample applications
```

and repeat the UI test. Now it sometimes (not sure the frequency or what else goes into it) fails to update the Topology view, though the notification popup does still appear, and navigating away and back shows the correct updated state. Also from other testing and examination of the database contents during this flow, the server and database really are updating their state correctly.

Anyway, I think this is a pretty minor bug since it only happens occasionally and is easily worked around by just clicking away and back.

**Comment by andrewazores** [comment]
Similarly I also see occasional instances where the Topology view does not update when a target discovery notification is received. Just now I had that happen when looking at the Topology view in an OpenShift deployment and a new KubernetesApi discovery occurred. The notification appeared but the view did not update until I navigated away and back.

**Comment by tthvo** [comment]
> Anyway, I think this is a pretty minor bug since it only happens occasionally and is easily worked around by just clicking away and back.

Ahh that's unfortunate. I can't see where the issue can be. Though, that being said, how about a refresh button somewhere in the toolbar to refresh the tree instead of navigating away? Not fixing the issue but could help a bit with UX.

**Comment by tthvo** [comment]
Right that makes sense...Now that I though of it, can't see where that refresh button fit in the UI either haha

**Comment by andrewazores** [comment]
This looks like it has been solved.
