### ISSUE TITLE
[Request] Integrate Common Expression Language (CEL) for Enhanced Expression Evaluation

### ISSUE THREAD

**Issue by aali309** [cryostatio/cryostat-web#1263]
### Describe the feature

see [https://github.com/cryostatio/cryostat-web/pull/1260#discussion_r1621423259](https://github.com/cryostatio/cryostat-web/pull/1260#discussion_r1621423259)

**Comment by andrewazores** [comment]
![image](https://github.com/cryostatio/cryostat-web/assets/3787464/5c278ec5-a4fa-4559-9d2b-fad5cbb0f6e0)

![image](https://github.com/cryostatio/cryostat-web/assets/3787464/97edfba7-b160-41a3-a123-21fe244d2176)

I think these are the three places where the text needs updating. The quick start text is probably separate, and the other two are likely a shared component.
