### ISSUE TITLE
[Bug] CI fails to produce container image

### ISSUE THREAD

**Issue by andrewazores** [cryostatio/cryostat-web#1288]
https://github.com/cryostatio/cryostat-web/actions/runs/9647421080/job/26606169227

> Error: initializing source docker-daemon:ghcr.io/cryostatio/cryostat-web:pr-1287-0625917845c11b696cf3077149185b3156db61c5: loading image from docker engine: Error response from daemon: {"message":"client version 1.22 is too old. Minimum supported API version is 1.24, please upgrade your client to a newer version"}

_Originally posted by @andrewazores in https://github.com/cryostatio/cryostat-web/issues/1287#issuecomment-2186797095_

**Comment by tthvo** [comment]
Looks related: https://github.com/containers/image/issues/2259.
