### ISSUE TITLE
[Bug] Web UI on cryostat demo page doesn't load

### ISSUE THREAD

**Issue by maxcao13** [cryostatio/cryostat-web#1310]
### Current Behavior

![image](https://github.com/user-attachments/assets/fea533a8-545d-41bf-903d-aa21a76db5c8)
Seems like it never loads. This is what I see in my console.

![image](https://github.com/user-attachments/assets/00a2dca5-b7e3-4dca-8902-3bdcc34a5738)

### Expected Behavior

The demo loading.

### Steps To Reproduce

Go to cryostat.io/demo

### Environment

```Markdown
- OS: Fedora 40
- Environment: Firefox
```

**Comment by tthvo** [comment]
Looks like there might have been an outage from the `surge.sh` side. I did experience the same issue for sometimes yesterday but it seems to be back online.

![image](https://github.com/user-attachments/assets/94dc28f0-bf40-454d-9ee1-59e88bef37f2)

**Comment by andrewazores** [comment]
Seems to be working for me now as well.
