### ISSUE TITLE
[Bug] Label/Annotation filtering for target nodes is broken

### ISSUE THREAD

**Issue by tthvo** [cryostatio/cryostat-web#1311]
### Current Behavior

The label/annotation filtering for target nodes is broken as it is now showed as below:

![image](https://github.com/user-attachments/assets/6d35cd72-9cac-45ca-8a0a-c9207597c52d)

### Expected Behavior

The labels show as `key=value`.

### Steps To Reproduce

1. `bash smoketesh.bash` on latest `main`.
2. Open `https://localhost:8443`
3. Go to Topology View
4. Select filter by Target Label or Annotation.
5. Click on the search input to show available options.
6. The `[object Object]` is displayed.

### Environment

```Markdown
- OS: Fedora 40
- Environment: `docker-compose` with smoketest
- Version: Cryostat 4.0.0-dev
```

### Anything else?

Potentially affected `3.0.0` release.

**Comment by tthvo** [comment]
Looks like some regressions when labels/annotations change their representations to `[{key: "my-key", value: "my-value"}]` list.

**Comment by andrewazores** [comment]
Confirmed that this is present in 3.0.0.

**Comment by andrewazores** [comment]
I also never realized before, but we render recording labels like `template: Profiling`, but Topology node labels/annotations like `version=1.20`. I'll clean that up with the same PR.

**Comment by andrewazores** [comment]
Actually, I'll split that change out, since we should backport the bug fix only.

**Comment by tthvo** [comment]
> I also never realized before, but we render recording labels like template: Profiling, but Topology node labels/annotations like version=1.20. I'll clean that up with the same PR.

Ah yes, about this tho, the topology is following `key=value` convention on the OpenShift side. Should we follow that instead of `key: value`?

**Comment by andrewazores** [comment]
That's true. I'll adjust the PR.
