### ISSUE TITLE
Enhanced Notifications handling

### ISSUE THREAD

**Issue by andrewazores** [cryostatio/cryostat-web#165]
After #162 is resolved, further enhancements to Notifications handling should be made, matching backend enhancements in rh-jmc-team/container-jfr#354 .

**Comment by jan-law** [comment]
This issue seems related to #284 and #267. Were there any other improvements you were thinking of?

**Comment by andrewazores** [comment]
I think that more or less covers it, really. I'll close this issue as superceded by those two.
