### ISSUE TITLE
Notification Categories

### ISSUE THREAD

**Issue by andrewazores** [cryostatio/cryostat-web#268]
Since #245 / #255, notifications go into a drawer with the most recent entry at the top, organized purely chronologically. It might be more useful for users if notifications were grouped by either notification category (as in WebSocket notifications channel "category" key), or by graphical notification level, and sorted chronologically within those categories.

**Comment by jan-law** [comment]
If you look at my rough demo screenshots, I wanted to separate the notifications that confirm user actions from the notifications that show target info. The warnings/errors have their own category to make it easier for users to find the error again after they close the toast notification. What do you think of the notification category grouping and header titles? 

Also, if there are many “Completed Actions”, the “Network Info” and “Problems” headers aren’t visible until you scroll down, which could be confusing if users see an error toast notification and don’t know where the notification went. 
[Patternfly guidelines](https://www.patternfly.org/v4/components/notification-drawer/design-guidelines) suggest no more than 3-4 categories and that only one category is expanded at a time. To fix the problem, I was thinking of automatically expanding the “Problems” category if there’s at least one unread error. What do you think?

![image](https://user-images.githubusercontent.com/84587295/132901539-a0b4e13c-0846-4fb0-81ac-3e2508153183.png)
![image](https://user-images.githubusercontent.com/84587295/132901635-730bad3d-660e-4e00-857f-d9ccd966f87e.png)
![image](https://user-images.githubusercontent.com/84587295/132901655-27d4cb23-5fd5-49d5-83b5-ddf95f23cf5a.png)
![image](https://user-images.githubusercontent.com/84587295/132901684-ba192a90-0aed-4725-a46e-cb3e10aa9476.png)

**Comment by andrewazores** [comment]
> I was thinking of automatically expanding the “Problems” category if there’s at least one unread error. What do you think?

That sounds like a really good idea to me. Looks excellent so far.
