### ISSUE TITLE
Notification Categories are inconsistent between actions

### ISSUE THREAD

**Issue by andrewazores** [cryostatio/cryostat-web#284]
As a side note, while testing this I notice that "Recording Created" appears twice - once as a success and once as an info with more details. "Recording Archived" appears once, as an info. It's probably a good thing that this notification grouping makes this kind of detail about the notifications more obvious/visible. I'll file a separate issue for that.

_Originally posted by @andrewazores in https://github.com/cryostatio/cryostat-web/issues/283#issuecomment-919535403_

**Comment by jan-law** [comment]
How did you reproduce the doubled 'Recording Created' notifications? I usually see one ‘recording created’ notification for cryostat:9091 or cryostat:9093 using any template:
![image](https://user-images.githubusercontent.com/84587295/133501398-7b31901e-bb4d-43fd-b59d-fa7865608283.png)

**Comment by andrewazores** [comment]
https://github.com/cryostatio/cryostat-web/blob/main/src/app/Shared/Services/Api.service.tsx#L214

https://github.com/cryostatio/cryostat-web/blob/main/src/app/RecordingList/ActiveRecordingsList.tsx#L142

The ApiService sends a notification like what you have in your screenshot, but the recording list component also sends a notification with more details. I think that one is likely only triggered if you create the recording by going to `Recordings` and pressing the `Create` button, not by starting from `Event Templates` and doing `Create Recording...`

**Comment by andrewazores** [comment]
I think in this specific case what we probably want is to remove the confirmation that comes from the Api.service on the 200 response, and instead only keep the confirmation that appears after a WebSocket notification comes in telling us the recording was created - and the subscription to this notification category should be somewhere long-lived, not within the recording list component.

This way, if some other client creates a new recording, I will also see that notification appear in my client, so I can be made aware of state changes that occur for any reason at any time, regardless of what view I am looking at at the moment.
