### ISSUE TITLE
Improve navigation item grouping

### ISSUE THREAD

**Issue by jan-law** [cryostatio/cryostat-web#302]
[#299 comment](https://github.com/cryostatio/cryostat-web/pull/299#pullrequestreview-765800028)

**Comment by jan-law** [comment]
@andrewazores What kinds of items would be displayed on the Dashboard page in the future? I only see a list of targets.

**Comment by andrewazores** [comment]
That's a large and open question. I don't have any solid answers at this time.

**Comment by jan-law** [comment]
No worries, in that case, I'll think about grouping the categories we have at the moment
