### ISSUE TITLE
Bad error handling when WebSocket connection fails

### ISSUE THREAD

**Issue by andrewazores** [cryostatio/cryostat-web#338]
The web client is using that URL as well, and getting this response:
`{"meta":{"category":"WsClientActivity","type":{"type":"application","subType":"json"},"serverTime":1636572394},"message":{"172.17.0.2:43696":"accepted"}}`

Before I receive the above error, I also see this appear once:
```
14:30:59.640 {} Login.service.tsx:116:23
    checkAuth Login.service.tsx:116
    RxJS 55
        innerSub
        _error
        error
        _error
        error
        tap
        _error
        error
        _error
        error
        _error
        error
        _error
        error
        fromPromise
        (Async: promise callback)
    fromPromise
        _trySubscribe
        subscribe
        errorContext
        subscribe
        doInnerSub
        outerNext
        _next
        next
        fromFetch
        (Async: promise callback)
    fromFetch
        _trySubscribe
        subscribe
        errorContext
        subscribe
        mergeInternals
        mergeMap
        operate
        subscribe
        errorContext
        subscribe
        take
        operate
        subscribe
        errorContext
        subscribe
        throwIfEmpty
        operate
        subscribe
        errorContext
        subscribe
        tap
        operate
        subscribe
        errorContext
        subscribe
        map
        operate
        subscribe
        errorContext
```

_Originally posted by @ebaron in https://github.com/cryostatio/cryostat-operator/issues/295#issuecomment-965673022_

**Comment by andrewazores** [comment]
https://github.com/cryostatio/cryostat-operator/pull/295#issuecomment-965579750

```
12:25:47.616 undefined NotificationChannel.service.tsx:224:19
    logError NotificationChannel.service.tsx:224
    error NotificationChannel.service.tsx:196
    RxJS 14
    next NotificationChannel.service.tsx:194
    RxJS 13
    setSessionState Login.service.tsx:184
    next NotificationChannel.service.tsx:188
    RxJS 8
    next NotificationChannel.service.tsx:194
    RxJS 13
    setSessionState Login.service.tsx:184
    next NotificationChannel.service.tsx:188
    RxJS 8
    next NotificationChannel.service.tsx:194
    RxJS 13
    checkAuth Login.service.tsx:109
    RxJS 7
```

https://github.com/cryostatio/cryostat-web/blob/dd715af2f3e85193c780a72331d97e0093cdadaf/src/app/Shared/Services/NotificationChannel.service.tsx#L224

`err.stack` and `err.message` should not be directly accessed without first checking that `err` is actually defined. The safe-navigation operator would probably be useful here, ie `err?.stack`.

**Comment by andrewazores** [comment]
This also applies to `v2` for the same reason, although the line number is a bit different: https://github.com/cryostatio/cryostat-web/blob/v2.0.0/src/app/Shared/Services/NotificationChannel.service.tsx#L157

**Comment by andrewazores** [comment]
@jan-law could you take a look at this? When we observe this occurring in the originally linked Operator PR, it's at least related to or likely even the cause of the web-client failing to reconnect to the backend about once very minute. I'm not sure what the reason is for the websocket connection to fail in the first place and why a reconnection is necessary (perhaps it has to do with the Minikube nginx ingress setup), but reloading the web-client causes this new application instance to successfully connect to the notifications channel initially, which tells me that the underlying connection can still be (re)established. Therefore, the existing client instance should also be able to successfully reconnect when it notices that the connection has been closed.

**Comment by jan-law** [comment]
I noticed if I leave the web UI idle for 60 seconds or longer, the WebSocket errors appear exactly every 60s for as long as the UI is idle. The WebSocket [close code](https://www.rfc-editor.org/rfc/rfc6455#section-7.4.1) shows 1006 without an error message. If I start interacting with the web UI, the errors stop appearing.

> perhaps it has to do with the Minikube nginx ingress setup

From the [nginx docs](http://nginx.org/en/docs/http/ngx_http_upstream_module.html#keepalive), there's a setting called `keepalive_timeout` with a default value `Default: keepalive_timeout 60s;`. The description says `Sets a timeout during which an idle keepalive connection to an upstream server will stay open`. Could this be related?

Also, the `keepalive` connection settings specify "for HTTP, the proxy_http_version directive should be set to “1.1” and the “Connection” header field should be cleared":
```
proxy_http_version 1.1;
proxy_set_header Connection "";
```

I'd like to check our ingress setup. Where are these ingress settings configured?

**Comment by andrewazores** [comment]
> I'd like to check our ingress setup. Where are these ingress settings configured?

I think what you want is here: https://github.com/cryostatio/cryostat-operator/blob/main/internal/controllers/cryostat_controller.go#L459

The nginx and HTTP headers you've found sound relevant and likely do explain the `1006` closes - I don't know exactly how the Minikube Ingress is working, but if it's using nginx as an HTTP proxy and forwarding the WebSocket connections through, then that would explain why there seems to be a behaviour difference between that and OpenShift Routes.

Since the web-client can successfully reconnect on a reload, I think addressing the `err.stack` and `err.message` accesses when `err` is nullable is a worthy first step patch to fix this problem. It would mean that every 60s periodically the WebSocket connection would still be closed, but at least it would successfully reconnect afterward. Finding and potentially correcting whatever Ingress configuration causes the 60s disconnects would be another great improvement that could follow along later, since that would be -operator side.
