### ISSUE TITLE
[Story] Deletions should prompt for confirmation

### ISSUE THREAD

**Issue by andrewazores** [cryostatio/cryostat-web#382]
When the user deletes an active or archived recording or an automated rule, they should be presented with a prompt confirming this destructive action. The prompt should contain some contextual information about what is being removed and the consequences for doing so (eg explain what it means to delete an active recording, or to delete an archived recording). For the case of automated rules there should also be a checkbox or toggle to set the value of the `?clean={boolean}` query parameter, with an explanation of what "cleaning" means when deleting a rule.

Finally, there should also be a checkbox on the prompt that says something like "do not ask me for confirmation again", which stores a user preference in local storage to skip displaying the prompt in the future and to implicitly pass. This preference should be exposed in the user settings menu as well so that the user can enable/disable the prompts at will.

Tasks:
- [ ] #462
- [ ] [Task] Add deletion prompt for custom Event Templates
- [ ] [Task] Add deletion prompt for Automated Rules
- [ ] [Task] Add deletion prompt for JMX Credentials
- [ ] add task for "do not ask again" feature

**Comment by andrewazores** [comment]
Deleting an Event Template or JMX Credentials should also have a prompt.

**Comment by maxcao13** [comment]
Should the "Do not ask again" feature have Settings per deletion warning type (e.g. Recordings, Credentials, Rules, etc.) or should it be for all deletion warnings?

**Comment by andrewazores** [comment]
Sure, doing it for each deletion type works. I was picturing it as a general setting for all of them, but doing it like the Notifications settings where there's a general checkbox for everything as well as fine-grained checkboxes for each type is nice, too.
