### ISSUE TITLE
[Task] Revamp/Redesign "All Archives" view

### ISSUE THREAD

**Issue by andrewazores** [cryostatio/cryostat-web#400]
https://github.com/cryostatio/cryostat-web/pull/397#issue-1175999375

> A table is not the best view for the new "All Targets Archives", but it's what works for now and is easily implemented since it's largely a copy-paste. Ideally however I think this should either be a Tree view (https://www.patternfly.org/v4/components/tree-view), or some kind of split-pane file explorer view like midnight commander or ranger. I'm not sure yet how to best incorporate the recording metadata/labels or other properties alongside a tree view, along with bulk operations for deleting recordings or whole folders. This is a stretch goal for this release and can be held for the next one.

**Comment by hareetd** [comment]
> I'm not sure yet how to best incorporate the recording metadata/labels or other properties alongside a tree view, along with bulk operations for deleting recordings or whole folders. 

After experimenting with `TreeView`, it doesn't seem like all the usual properties/actions for an Archived Recording can be implemented (it's not as flexible as a `Table`). However, I think a [nested table](https://www.patternfly.org/v4/components/table/#composable-expandable-with-nested-table) could be a decent alternative. The parent rows of the table would be the targets themselves, which could be expanded to reveal a nested table consisting of the archived recordings for each target. Thoughts?

**Comment by andrewazores** [comment]
That sounds pretty good to me.

**Comment by hareetd** [comment]
![image](https://user-images.githubusercontent.com/41028544/167486642-7c5baec7-b42e-4df5-849b-a13904fc9e14.png)

This is currently how it looks. Besides making it look nicer, I'll be adding other features including a search function, a scrollbar, and prompting for auth when a target is clicked (i.e. what `TargetSelect` does). I was also thinking of adding another `Card` below with a `Table` of recordings uploaded directly to archives. 

However, in order to update the state of this table, I need to implement backend changes to help differentiate between target-specific archived recordings vs. uploaded ones. Perhaps putting the uploaded recordings into an `archives/uploads/` subdirectory instead of the current unlabelled archives subdirectory along with a beta `UploadedRecordingsGetHandler` to retrieve recordings from this new subdirectory. Thoughts?

**Comment by andrewazores** [comment]
> and prompting for auth when a target is clicked (i.e. what TargetSelect does)

Is this needed on this view? The auth prompt is for JMX credentials, but you don't need any JMX connections to just query the archives.

> Perhaps putting the uploaded recordings into an archives/uploads subdirectory instead of the current unlabelled archives subdirectory

That sounds reasonable. If the "unlabelled" archives subdirectory is getting renamed then we also need to make a note of this and have some kind of migration step, preferably automatic, so that the directory structure change doesn't result in any lost data or data that can't be retrieved through the API.

> UploadedRecordingsGetHandler

This I'm not so sure about. From the name I gather the intent is to only return the contents of that unlabelled/uploaded archives subdir?

This seems to me like a good fit for a GraphQL query instead, so it's flexible:

`queries.graphqls`
```graphql
type Query {
  targetNodes(filter: TargetNodesFilterInput): [TargetNode!]!
  archivedRecordings(filter: ArchivedRecordingsFilterInput): [ArchivedRecording!]!
}
```

This way it can return a view for the whole archives, or filtered on the server during the request processing. This also brings it closer in line with the target-specific Archives view, which also uses GraphQL via the `targetNodes` top-level query. I think this also lends itself well to your idea for a "search" feature.

We already have an `ArchivedRecordingsFilterInput` that allows for filtering the results by recording name and labels, so either that can gain a `string` for exact matching of the source target (ie the archive subdirectory name), or this new query can use a new `FilterInput` that adds that additional capability and we leave out that capability for the already existing queries using that filter input.

There is also plenty of documentation out there about how to implement things like pagination using GraphQL:
https://graphql.org/learn/pagination/
I would suggest leaving out the pagination for now, since that's a good feature that we should look at adding to all GraphQL queries, as well as to any `v2.2` API handlers we add (and maybe retrofit to `v2/v2.1`s too).

**Comment by hareetd** [comment]
> This behaviour could be embedded into the `entrypoint.sh` perhaps, but I think it fits best as a migration script step. Maybe there's a way we can get the Operator to perform this kind of migration automatically.

I like the idea of using the Operator if possible; I can look into it once the backend and frontend changes for this PR are ready.

>  Ideally a paginated UI is supported by an actual paginated API request, so that the request isn't transferring a bunch of unnecessary data on each load, or performing more querying on the back end than actually needed to display the first page of content.

Ah, of course. That makes sense, thanks.
