### ISSUE TITLE
[Task] Automated Rules form should list Event Templates for the selected target

### ISSUE THREAD

**Issue by jan-law** [cryostatio/cryostat-web#433]
Not sure if this is a bug or not, but if you start an automated rule using the web UI and smoketest with MatchExpression `true` and `template.name: Cryostat`, I only see one recording started on the Cryostat container. Is this intentional?

**Comment by andrewazores** [comment]
Now, new question: what templates do we display when the user has not selected any target? Perhaps they do not currently have any target to select, but they want to create an Automated Rule in advance before deploying their application.

In that case perhaps we should query ourselves and filter out the one with `Provider: Cryostat`

**Comment by maxcao13** [comment]
This may be a stupid question but, how do you test using `smoketest.sh` or `run.sh` while also using `cryostat-web`?

**Comment by andrewazores** [comment]
`CRYOSTAT_CORS_ORIGIN=http://localhost:9000 CRYOSTAT_DISABLE_SSL=true sh smoketest.sh` in one terminal, `yarn start:dev` in another.
