### ISSUE TITLE
'Archive' and 'Delete' buttons still enabled after deleting all recordings

### ISSUE THREAD

**Issue by jan-law** [cryostatio/cryostat-web#437]
Create one recording and select it. The Archive and Delete buttons should become enabled. Then open a second web-client in a new tab and delete that recording. Now both tabs show an empty flight recording table, but the first web client's Archive and Delete buttons are still enabled. Clicking those buttons doesn't do anything.

![image](https://user-images.githubusercontent.com/84587295/169091421-162f7054-5ee7-4648-99c6-492a76d1a916.png)

**Comment by jan-law** [comment]
I'm assigning myself to this because it's causing an error in #428 and I'd like to open that PR soon

**Comment by andrewazores** [comment]
@dfitzmau @kucollin new Known Issue for 2.1.0

**Comment by andrewazores** [comment]
#438 has fixed the case where a single recording exists, is selected, and then is deleted by another client, but I seem to still be able to reproduce this if I try the same procedure with multiple recordings present and more than one selected in the original client.
