### ISSUE TITLE
[Task] Deleting archived recordings can delete wrong file for identically-named but distinct files

### ISSUE THREAD

**Issue by andrewazores** [cryostatio/cryostat-web#445]
This problem of `/api/v/recordings/:recordingName/etc` endpoints being unable to differentiate between per-target archives and the uploaded archives is actually affecting more than just labels, too. Deleting an archived recording also runs into problems since the file is searched for by name, but can be found in two locations.

_Originally posted by @andrewazores in https://github.com/cryostatio/cryostat-web/issues/442#issuecomment-1143942713_

**Comment by hareetd** [comment]
Adding a `GET /api/beta/recordings/:sourceTarget/:recordingName` to the backend would be a simple fix with minimal corresponding changes on the frontend. Thoughts?

**Comment by hareetd** [comment]
I think similarly modified beta versions of the `RecordingGetHandler` and `ReportGetHandler` are also warranted, since they also assume a unique recording name.

**Comment by andrewazores** [comment]
Yea, target-oriented handlers for each of those uses sounds like the right fix.

**Comment by andrewazores** [comment]
See also https://github.com/cryostatio/cryostat/issues/1045 when working on the backend implementation discussed above. The fix applied to the existing handler should also be present in the new handlers.
