### ISSUE TITLE
[Story] Upload/download Automated Rules files

### ISSUE THREAD

**Issue by andrewazores** [cryostatio/cryostat-web#447]
As a user, I would like the ability to upload Automated Rule definition files (JSON format) through the web-client, rather than having to step through the form view every time. This would be an enhanced workflow for advanced users because it's quicker and easier to make many copies of similar rules by bulk editing text files locally than to click through the UI every time.

Complementary to that, I would also like the ability to download Automated Rule definition files (JSON format) from Cryostat to my workstation. This would make it easier for me to copy my configurations between Cryostat installations, or allow me to ensure my rules are backed up prior to Cryostat version upgrades. It would also make it quick and easy to make modifications to existing rule definitions since I could download the file, edit it locally with my preferred text editor, and then delete the old rule from Cryostat and upload my new modification in its place, again without having to click through the guided UI.

Tasks:

- [ ] #448
- [ ] #449

**Comment by tthvo** [comment]
@andrewazores Do we have a sample rule file in json that resembles entering the form on the web UI? 

I saw this one but I am not sure how its matched with the UI flow and it seems not to include all fields?

```
{
  "connectUrl": "service:jmx:rmi:///jndi/rmi://cryostat:9091/jmxrmi",
  "alias": "io.cryostat.Cryostat",
  "labels": {},
  "annotations": {
    "platform": {},
    "cryostat": {
      "HOST": "cryostat",
      "PORT": "9091",
      "JAVA_MAIN": "io.cryostat.Cryostat"
    }
  }
}
```

**Comment by andrewazores** [comment]
I don't have a sample rule JSON file, but you can generate one yourself easily enough. If you run `sh smoketest.sh`, the container is configured to run with some directories within the project mounted as storage locations. Rules you create through the UI will be saved in `./conf/rules`.

As far as how a rule definition matches the UI flow, well, it's pretty close to 1:1. The UI might relabel certain elements to make the names more descriptive or useful, but in the end it really is just creating a rule definition and `POST`ing it to the backend. You can try using your browser's devtools network tab and observe the request fired when you create a rule definition and see what form fields correspond to the UI elements.

**Comment by tthvo** [comment]
oh right I will take a look at that! Thanks :D
