### ISSUE TITLE
[Task] Implement nested table for `matchExpression` Credentials

### ISSUE THREAD

**Issue by andrewazores** [cryostatio/cryostat-web#466]
Parent: https://github.com/cryostatio/cryostat-web/issues/465

> https://github.com/cryostatio/cryostat/pull/1000 adds a new API call that should be used for a revamped JMX Credentials view within the Security section. This structure seems well-suited to a table where each row corresponds to a matchExpression, and the row can be expanded to reveal a nested table of targets.
>
> The matchExpression rows should be selectable, including with a header checkbox to select all, so that the row can be deleted. This deletion operation is partially supported in https://github.com/cryostatio/cryostat/pull/1000 - the internal call exists, but there is no v2.2 API handler for the deletion yet.

**Comment by hareetd** [comment]
![image](https://user-images.githubusercontent.com/41028544/182946151-2ecb9409-d4b5-4a1c-9447-bd4c74915526.png)

I'm thinking of adding a count of the number of matched targets for each match expression. Would it be fine to modify the `CredentialsGetHandler` to also return such a count alongside the `id` and `matchExpression`? Or would a new GraphQL query be preferable? 

I'm following a similar workflow to the `AllTargetsArchivedRecordingsTable` when it comes to data querying. Expanding a match expression row sends a request to the `CredentialGetHandler` for the targets list.

**Comment by andrewazores** [comment]
I think you can just add the count inside the response from the existing handler in this case.
