### ISSUE TITLE
[Task] Recordings view causes excessive GraphQL queries

### ISSUE THREAD

**Issue by andrewazores** [cryostatio/cryostat-web#489]
![2022-07-29T11:48:19,140025978-04:00](https://user-images.githubusercontent.com/3787464/181796671-7061b7d9-ef47-4a39-b614-62257477fde1.png)

Since https://github.com/cryostatio/cryostat-web/commit/6a70f83705a88badb572a84982bde4c76eff6923, visiting the Recordings view and selecting a target JVM results in a large number of GraphQL queries being made.

In my case I see that all of the GraphQL queries have the following POST request body query:

```graphql
              query {
                targetNodes(filter: { name: "service:jmx:rmi:///jndi/rmi://carbon:9091/jmxrmi" }) {
                  recordings {
                    active {
                      name
                    }
                    archived {
                      name
                    }
                  }
                }
              }
```

**Comment by andrewazores** [comment]
@tthvo @maxcao13 either of you interested in taking a look at this?

**Comment by tthvo** [comment]
Suree I can look into this :D I will ask Max for some help too!
