### ISSUE TITLE
[Task] Cannot add labels to new recording using CreateRecording form

### ISSUE THREAD

**Issue by maxcao13** [cryostatio/cryostat-web#500]
1. Create a recording using the CreateRecording form on any target and set metadata
2. The metadata labels are not updated with the new label.

Editing the recording afterwards with new labels is completely fine however.

**Comment by tthvo** [comment]
I think this is the issue (the function is passed, but is expected to get called):

https://github.com/cryostatio/cryostat-web/blob/4c3aa111d088424a2b31a52f5bf4b54f9f72eb18/src/app/CreateRecording/CustomRecordingForm.tsx#L182
