### ISSUE TITLE
[Task] Implement finer-grained recording duration filter

### ISSUE THREAD

**Issue by andrewazores** [cryostatio/cryostat-web#512]
Speaking of toolbars, I just noticed something about the `Duration` filter in the toolbar.

The two "started before/after" filters have a magnifying glass search button to perform the filter after selecting the date/time parameters. The other filters have a dropdown menu (`Select`) and selecting an item immediately starts the filtering with that item. All good so far.

For the Duration filter, clicking the `Continuous` checkbox starts filtering for recordings with a `continuous` duration. Unchecking the box removes the filter. There doesn't seem to be a way to filter for recordings that are *not* continuous, other than by using the numeric duration filter.

The numeric duration filter only allows for matching exact recording durations, not greater-than or less-than, which I think is okay (for now), but to actually add this filter the user has to click the numeric input field and then press Enter.

Here's my idea for how to make this filter control a little more intuitive, at least to me:

1. Add a magnifying glass button like the "started before/after" filter which actually adds a filter based on the selected criteria
2. Remove the static "Continuous" checkbox
3. Add a `Select` with values `Continuous`, `Greater Than`, `Less Than`
4. Add a secondary control that varies according to the value selected above:
4a. If `Continuous`, dynamically display a "Continuous" checkbox. The state of this checkbox becomes a "continuous == state" filter when the magnifying glass is clicked. This way the user can filter by only continuous recordings, or only fixed durations
4b. If `Greater Than` or `Less Than`, dynamically display a duration picker. I think this should match the duration field on the recording creation form, with a number input and a separate units input. When the magnifying glass is clicked then apply a filter that looks for recordings fitting the specific criteria, ex. "recordings with fixed duration less than 5 minutes".

This is best suited for a separate PR, in any case.

_Originally posted by @andrewazores in https://github.com/cryostatio/cryostat-web/issues/503#issuecomment-1251371498_

**Comment by tthvo** [comment]
This and #616 are implemented after upgrades to PF5 in #1303 :D

**Comment by andrewazores** [comment]
Done in #1303
