### ISSUE TITLE
[Task] Cryostat logo should be responsive and size-constrained

### ISSUE THREAD

**Issue by tthvo** [cryostatio/cryostat-web#514]
Our logo seems to be render pretty oddly (i.e. quite large). I think we might need a set of responsive logos and add some size constraints to them.

![Screenshot from 2022-09-20 12-03-27](https://user-images.githubusercontent.com/68053619/191313561-5cdddd01-7a09-4e79-a6c6-c554b79fd469.png)

**Comment by tthvo** [comment]
Any thoughts on this @andrewazores? I heard we are redesigning the logo, so I guess we wait?

**Comment by andrewazores** [comment]
That's odd. It renders like this for me:

![image](https://user-images.githubusercontent.com/3787464/191318857-bdaece1b-512e-4147-9f66-4f6a76b5c4a7.png)

That image is an SVG, so it doesn't have an intrinsic size of its own. It's used [here](https://github.com/cryostatio/cryostat-web/blob/13d9d45e705c4eddcfb4a31dfeaca2a1236abd37/src/app/About/About.tsx#L50), so the [Brand component](https://www.patternfly.org/v4/components/brand) is probably relevant.

Which browser are you using here? My screenshot was taken from Firefox 104.

**Comment by andrewazores** [comment]
Anyway yes, we do have some background work in progress to redo the logo(s). With that there will presumably be a new SVG for the redesigned logo. If there is some bug in how styling and responsive sizing is done then we can still fix that independently of replacing the SVG file.

**Comment by tthvo** [comment]
> That's odd. It renders like this for me:
> 
> ![image](https://user-images.githubusercontent.com/3787464/191318857-bdaece1b-512e-4147-9f66-4f6a76b5c4a7.png)
> 
> That image is an SVG, so it doesn't have an intrinsic size of its own. It's used [here](https://github.com/cryostatio/cryostat-web/blob/13d9d45e705c4eddcfb4a31dfeaca2a1236abd37/src/app/About/About.tsx#L50), so the [Brand component](https://www.patternfly.org/v4/components/brand) is probably relevant.
> 
> Which browser are you using here? My screenshot was taken from Firefox 104.

Ahh that's interesting. I am using FireFox `104.0.1` :D. I think it also happens if i check on Chrome.

**Comment by andrewazores** [comment]
I see the same oversized logo rendering on the About page now, too. I think it must have come in with a recent PR. I'll bisect it soon.

**Comment by andrewazores** [comment]
It looks like the first bad commit was [e1fcd042b3494e5f1d17a3b6b32915fbec9f46c5](https://github.com/cryostatio/cryostat-web/commit/e1fcd042b3494e5f1d17a3b6b32915fbec9f46c5). Not sure why it wasn't looking like that for me before. This makes sense though, that commit updated the patternfly version
