### ISSUE TITLE
[Task] Add UI for adding metadata to uploaded archived recordings

### ISSUE THREAD

**Issue by maxcao13** [cryostatio/cryostat-web#521]
I think all we need to do about the uploading metadata issue now is to update the web-client to handle the recent merge https://github.com/cryostatio/cryostat/pull/1063 with this associated PR https://github.com/cryostatio/cryostat-web/pull/499 ?

_Originally posted by @maxcao13 in https://github.com/cryostatio/cryostat/issues/1047#issuecomment-1248490502_

**Comment by tthvo** [comment]
Related to #510

**Comment by maxcao13** [comment]
Oh, I didn't see the other issue guess this is a duplicate then.
