### ISSUE TITLE
[Task] Refactor code around UploadsTable and ArchivesRecordingTable

### ISSUE THREAD

**Issue by maxcao13** [cryostatio/cryostat-web#522]
I think the `props.target` passed to ArchivedRecordingTable mostly for UploadsTable as it does not have target. I think we could either:

1. Create a separate component for UploadsTable
2. Rename props and add checks if we should use `context.target` or fixed `props.target`).

_Originally posted by @tthvo in https://github.com/cryostatio/cryostat-web/pull/499#discussion_r980468975_

**Comment by tthvo** [comment]
Looks like `props.target` is passed with `context.target` anyways (if not upload) so we can just use it.
