### ISSUE TITLE
[Task] JMX Auth Modal prompt does not appear on Automated Rules creation form

### ISSUE THREAD

**Issue by andrewazores** [cryostatio/cryostat-web#527]
When viewing the Automated Rules creation form we query the backend for the event templates available for the selected target JVM (if any is selected). This opens a JMX connection and therefore may require JMX credentials to be passed or stored so that Cryostat can check the TARGET templates. A similar data flow occurs on the Recordings and Events views, and a modal dialog appears prompting the user to enter JMX credentials. On the Automated Rule creation view the connection and HTTP request simply fail if credentials are required and an error notification appears. The standard JMX credentials auth modal should appear instead and, just like for Recordings/Events, the request should automatically re-fire if credentials are saved so that the event template selector can populate.

**Comment by maxcao13** [comment]
Seems like a query like `http :8181/api/v1/targets/$(echo -n service:jmx:rmi:///jndi/rmi://cryostat:9091/jmxrmi | jq -sRr @uri)/templates  "Authorization: Basic dXNlcjpwYXNzCg"` returns error code 500 if credentials are not stored, when it should probably return 427? Looks like `AbstractAuthenticatedRequestHandler` should be handling it correctly but seems like somethings off. Any thoughts @andrewazores?

**Comment by andrewazores** [comment]
I can take a look. I just noticed the buggy behaviour and filed the issue, no deeper investigation into root causes. I'm not sure if this case was ever actually tested either - it may have always been broken on the rule creation form.
