### ISSUE TITLE
[Task] Add a view for users to find all archives without target-specificity 

### ISSUE THREAD

**Issue by maxcao13** [cryostatio/cryostat-web#546]
> Somewhat off-topic: While working on this I had the realization that in the important deployment scenarios, ex. k8s/OpenShift, the JMX Service URL is generally going to contain a service IP address rather than some resolvable DNS hostname. This means that the migration/transfer work we do is unlikely to be triggered to begin with, because a restarted instance may not appear to be "the same" target, as both its JMX Service URL and its JVM ID will have changed. In that kind of case I think it's OK that we don't associate the old archives to the new target instance, however, we DO need to provide the user a way to access those archives still. Just because the target has gone offline and wasn't replaced doesn't mean the user doesn't still need those archives. That's mainly a frontend problem, but we might need to tweak some of our queries to suit.

> Anyway, I think adding a query akin to the old-style `GET /api/v1/recordings` is what we need to ensure the user can find those recordings from old targets that we don't see any replacement for. IMO this should probably be the new underlying query for the frontend's All-Archives view. Rather than getting the list of known targets and then grabbing the corresponding archived recording information for those targets only, it needs to be essentially just a view of the archives and the subdirectories, with no consideration for which of those correspond to currently-known targets.

_Originally posted by @andrewazores in https://github.com/cryostatio/cryostat/issues/1105#issuecomment-1272148324_

**Comment by andrewazores** [comment]
That said I think this feature really needs to get (back) in for the next release, and the feature freeze date is this coming Friday. So if it's infeasible to get everything in place to implement the nested view I'm describing then I am OK with just bringing back the flat file listing view like you have shown.
