### ISSUE TITLE
[Task] Web assets should not be cached across version changes

### ISSUE THREAD

**Issue by tthvo** [cryostatio/cryostat-web#563]
Seems like the way web assets is currently built causes the browser to cache assets if downgrading to older version of Cryostat. From previous discussions:

The issue: 

> I've just been trying to run the cryostat 2.1.0 image directly off quay with CRYOSTAT_IMAGE="theimage", but im not sure where the web-assets are being used because i still see stuff from 2.2.0 when going to localhost:8181

Explanations:

> the way that the web-client build works, your browser may think that it already has up-to-date assets for the cryostat console and use cached versions rather than actually downloading the web-client from the cryostat instance you're connecting to if that's the case then a browser hard refresh (ctrl-shift-r or something) should fix it

> I guess the HTTP headers in use would be ones like If-Modified-Since, and if you're downgrading from a recent build to an older build, then the browser asks the cryostat vertx webserver how old the app.bundle.js is and decides not to download it because the browser has a newer file with the same name from the same origin despite the fact that the file has actually changed and probably has different other attributes like filesize, those attributes wouldn't be checked for

**Comment by andrewazores** [comment]
As this is worked on, a good way to test would be to simply run ex. `npm run build:notests ; ls -ltr dist` to see output like that above. Additionally, Firefox at least has a dev tools control in the Network tab that can simulate slower internet connection speeds, even to `localhost`, so this could be used to compare how the web-client loading process feels with slower connections. The optimizations we're talking about should basically lead to faster initial load time to get the page displaying to the user, correct the caching behaviour in cases where the assets have actually changed (this is the most important goal), but possibly lead to slight loading lags as the user navigates between views in the application and new components are loaded on-demand (the price paid for faster initial load).
