### ISSUE TITLE
[Task] JMC Agent Event Template action menu goes out of viewport

### ISSUE THREAD

**Issue by andrewazores** [cryostatio/cryostat-web#583]
![image](https://user-images.githubusercontent.com/3787464/198311358-a9a0ae10-7b88-4ff0-9662-c31c41886b78.png)

If the viewport is not scrolled all the way down before clicking the three-dots action menu, then the dropdown appears and goes outside the viewport. The viewport cannot be scrolled any further and so part of the content is just not reachable.

**Comment by tthvo** [comment]
Not sure but i am using Chrome and FireFox... I can still see it. However, we should add some space to accommodate the last bit of the menu that is out of viewport.

![Screenshot from 2022-10-27 13-26-06](https://user-images.githubusercontent.com/68053619/198358034-59995c5b-5a9a-4be9-9159-93d2359bd2b4.png)

**Comment by andrewazores** [comment]
I'm using Firefox. If I scroll all the way down before clicking the action menu I get a viewport that looks like yours, but if I scroll up a little from there so that the action menu is just on the edge of the viewport then the menu pops out basically offscreen entirely.
