### ISSUE TITLE
[Story] "Test connection" feature

### ISSUE THREAD

**Issue by andrewazores** [cryostatio/cryostat-web#592]
As a user, I do not want to have to update a connection configuration, attempt to load a content view, and then delete and recreate my connection configuration if I entered the wrong values by mistake.

- [ ] #593
- [x] #594

**Comment by tthvo** [comment]
Looks like we need to define an API endpoint to open a probe connection to the target. Just wondering if we can safely use any existing endpoint for this purpose?

**Comment by andrewazores** [comment]
I think reusing the existing custom targets definition endpoint makes sense. I would probably call the parameter `dryrun` or something, but `probe` could work too - though we already use that term in relation to the JMC Agent and inserting bytecode.

That endpoint handler is already basically set up to do what we need it to, since it will attempt to open a connection to the target and retrieve its hash ID before adding it to the discovery database. So the `probe/dryrun` parameter would just skip that last step. It looks like the handler also needs to notify the JVM ID cache to invalidate the ID entry if the definition is not actually added to the database, or maybe instead a way to retrieve the JVM ID without caching the result to begin with.
