### ISSUE TITLE
[Task] Implement time range selection for datetimepicker filter

### ISSUE THREAD

**Issue by tthvo** [cryostatio/cryostat-web#616]
Currently, we have to select `StartedAfterDate` and `StartedBeforeDate` to achieve this range selection. However, we should allow user to directly do this. I think we could merge 2 above filter options into just `Date` and if the user choose only 1 date, UI can display a operation dropdown (i.e. before or after).

Example: https://www.patternfly.org/v4/components/calendar-month#date-range

**Comment by tthvo** [comment]
I think this can be closed now :D

**Comment by andrewazores** [comment]
Done in #1303
