### ISSUE TITLE
Improve error messages/notifications

### ISSUE THREAD

**Issue by andrewazores** [cryostatio/cryostat-web#65]
https://github.com/rh-jmc-team/container-jfr-web/pull/59#discussion_r418271922

As in the pull request review above, the error messages sent from ContainerJFR could use some improvement. In some cases errors are only reflected in response status codes, with no meaningful payload text. In other cases there is payload text included, but this text may be simply raw, unformatted text (no JSON wrapping etc.), and with no particular well-established conventions. This makes it difficult for ContainerJFR Web or other clients to consume these messages and produce meaningful notifications for end users.

**Comment by andrewazores** [comment]
I don't have any specific examples - keep in mind that this issue was filed in April 2020, and things on both the frontend and backend side have already changed (improved, hopefully) a fair amount since then as well. I do think there are still cases where we can display better error messages, but I don't have any specifics in mind right now. I can take a look around and see if I can find things that need improvement.

**Comment by hareetd** [comment]
> I don't have any specific examples - keep in mind that this issue was filed in April 2020, and things on both the frontend and backend side have already changed (improved, hopefully) a fair amount since then as well.

Good point :P

> I can take a look around and see if I can find things that need improvement.

Sounds good, I appreciate it. I'll keep looking as well.
