### ISSUE TITLE
[Task] Target selection should allow filtering

### ISSUE THREAD

**Issue by tthvo** [cryostatio/cryostat-web#666]
Right now, the target select menu will just show a plain list and will expand as needed. I think we should limit its size and allow filters. Or perhaps a new design for this.

Related to #429

**Comment by andrewazores** [comment]
Sure, I like that idea. It's a good upgrade from where our UX is now at least. I think the question of how to display things when the user wants to select multiple targets, or a higher order node from the tree, is still open ("start a recording on every target below this Deployment"), but at least this way we get a way to visualize those higher order nodes and see some of the relationships between targets.
