### ISSUE TITLE
[Request] About modal should have Cryostat background image

### ISSUE THREAD

**Issue by tthvo** [cryostatio/cryostat-web#768]
## Describe the feature

Right now, we are using a default background image from Patternfly. We should be using our Cryostat's custom image.

![about-modal](https://user-images.githubusercontent.com/68053619/208175135-321e6cd3-ed8c-45e0-ac9d-c3e05e14db3e.png)

## Any other information?

References:  https://www.patternfly.org/v4/components/about-modal#custom-background-image

**Comment by tthvo** [comment]
@andrewazores Do you have any image in mind? Maybe from upstream doc *https://cryostat.io/assets/images/cryostat-homehero-bkg.png)? Or is this Patternfly default image good already?

**Comment by andrewazores** [comment]
That upstream docs image looks good.
