### ISSUE TITLE
[Task] "Sub"views should be routable

### ISSUE THREAD

**Issue by andrewazores** [cryostatio/cryostat-web#78]
For example, the Recordings view has a card with Active and Archived tabs. When visiting the route `/recordings`, the general top-level card view is what is routed and this defaults to displaying the Active tab. Both the Active and Archived tabs should be reachable by in-app routing, so that users can bookmark or link to specific subviews, and to ensure that view state is preserved as much as possible should the user close/reopen or refresh the browser tab.

**Comment by andrewazores** [comment]
Not sure that this will make sense without also including the target connection within the route as well, actually, unless *all* routable components are also built to include a "disconnected state", similar to an empty state, which can be displayed when they are routed to with no target connection selected.

**Comment by tthvo** [comment]
Now that we have Redux setup + localStorage. I think this is possible now.
