### ISSUE TITLE
Rebuilds without source changes should be faster

### ISSUE THREAD

**Issue by andrewazores** [cryostatio/cryostat-web#790]
Currently, running a rebuild without having made any source changes still takes a fairly long time. It should be possible to configure some Webpack caching so that unchanged files are not recompiled. We already have some configuration that should do this, but it doesn't seem to be working as expected, so perhaps some other step in the pipeline is not performing caching and this busts the later caches that are set up.

https://webpack.js.org/guides/caching/
https://javascript.plainenglish.io/how-to-improve-webpack-performance-7637db26fa5f

**Comment by tthvo** [comment]
I was checking this issue and saw this in log when saving an unchanged source file (e.g. any txs file).

```bash
assets by status 31.3 MiB [cached] 137 assets
asset index.html 7.63 KiB [emitted]
Entrypoint app 21.1 MiB (7.96 MiB) = 43 assets 67 auxiliary assets
cached modules 10.9 MiB (javascript) 8.94 MiB (asset) 33.4 KiB (runtime) [cached] 3548 modules
./src/app/Recordings/ActiveRecordingsTable.tsx 29.4 KiB [built]
webpack 5.75.0 compiled successfully in 475 ms
No errors found.
```

Seems to only compile the saved file. I suppose we also want to avoid such files' compiling?

**Comment by tthvo** [comment]
Also, seems like the first save of any file is pretty slow due some hot-reload module being generated. Cache, from [docs](https://webpack.js.org/configuration/cache/#cache), is said to be enabled by default with `memory`.

```bash
assets by status 31.3 MiB [cached] 136 assets
assets by path . 73.3 KiB
  assets by info 50.7 KiB [immutable]
    asset runtime.3d1d6a1fd45617ee.bundle.js 49.8 KiB [emitted] [immutable] (name: runtime)
    asset runtime.0d9883d8012a09a6.hot-update.js 847 bytes [emitted] [immutable] [hmr] (name: runtime)
    asset runtime.0d9883d8012a09a6.hot-update.json 31 bytes [emitted] [immutable] [hmr]
  asset favicon.ico 15 KiB [emitted]
  asset index.html 7.63 KiB [emitted]
Entrypoint app 21.1 MiB (7.96 MiB) = 44 assets 67 auxiliary assets
cached modules 10.9 MiB (javascript) 8.94 MiB (asset) [cached] 3530 modules
runtime modules 33.4 KiB 18 modules
./src/app/Recordings/ActiveRecordingsTable.tsx 29.4 KiB [built]
webpack 5.75.0 compiled successfully in 1329 ms
Type-checking in progress...
No errors found.
```

**Comment by andrewazores** [comment]
I was thinking of the `yarn build` case actually, not devserver builds.

**Comment by tthvo** [comment]
> I was thinking of the `yarn build` case actually, not devserver builds.

Ahh then I think probably because we set

https://github.com/cryostatio/cryostat-web/blob/c8b3b2cc35e384292ba21f53417fed7ef5c27a89/webpack.common.js#L163

to clean `/dist` directory before any build. Do you want to remove it?

**Comment by andrewazores** [comment]
Is that why? Seems unfortunate if so. Removing that would lead to cluttered `/dist` and therefore cluttered unused assets in the final Cryostat application image unless we're careful to add an explicit `yarn run clean` step in the CI builds that produce published images. How much performance difference does removing that config line have on `yarn build`?

**Comment by tthvo** [comment]
Hmm that was what I thought but it seemed like no much was improved. Perhaps, webpack does not even care what the content of `dist` is.

**Comment by tthvo** [comment]
I think this page https://webpack.js.org/configuration/cache said

> Cache the generated webpack modules and chunks to improve build speed. cache is set to type: 'memory' in [development mode](https://webpack.js.org/configuration/mode/#mode-development) and disabled in [production mode](https://webpack.js.org/configuration/mode/#mode-production).

I guess we can enable it for production build?

**Comment by andrewazores** [comment]
Sounds worth taking a closer look at at least. Please open a draft PR with these config changes so we can all try it out and see if we find any weird `dist/` contents after repeated builds or other unwanted build oddities.

**Comment by tthvo** [comment]
I opened it here at #791 :D
