### ISSUE TITLE
[Task] Collapse toolbar buttons

### ISSUE THREAD

**Issue by tthvo** [cryostatio/cryostat-web#828]
## Describe the feature

In small screen width, the buttons need to be collapsed so that it does not take it spaces. Another reason is to avoid overflowing. 

Currently, toolbar items are overflowing hidden, which is not very ideal. We can either make it scrollable or use flex to break lines.

## Screenshots

![Screenshot from 2023-01-19 14-21-36](https://user-images.githubusercontent.com/68053619/213539979-36d0b677-fd6d-4b9d-a68b-942afbac6f98.png)

![Screenshot from 2023-01-19 14-20-17](https://user-images.githubusercontent.com/68053619/213539981-b18c760c-75de-4e65-8c03-2ed690556f5d.png)

**Comment by andrewazores** [comment]
Related on the topic of rendering on narrow viewports, the Automated Rules table also doesn't do so well.

**Comment by tthvo** [comment]
Looks like even in regular or large viewports, overflow on Rule table still occurs if there is not enough space for entire row.
