### ISSUE TITLE
[Bug] Rendering odd whitespace at end of page

### ISSUE THREAD

**Issue by andrewazores** [cryostatio/cryostat-web#863]
![image](https://user-images.githubusercontent.com/3787464/217264290-303204e1-f99e-47d9-949d-24addf4eb879.png)

Notice the whitish band of space at the bottom of the image. I notice this when using my workstation with a 1920x1200 display.

It seems to be caused by https://github.com/cryostatio/cryostat-web/pull/858 . If I check out a commit before that, or locally revert that patch, then the same page looks like this (normal):

![image](https://user-images.githubusercontent.com/3787464/217264883-f05cbf6c-0c0c-468e-9a4a-5a2935c47149.png)

**Comment by tthvo** [comment]
@andrewazores I also see this when using PF topology extension. My issue was with the `skip-to-content` component in `AppLayout` and removing it fixed the issue. Is this the same?

**Comment by tthvo** [comment]
I guess we can remove that component for now (might lose some functionality for keyboard users and accessibility support) and keep the react-table version bump?

**Comment by andrewazores** [comment]
Needs more investigation, I think. If the `react-table` version bump isn't bringing us anything on its own then I would prefer to keep the SkipToContent component. But, it's not necessarily clear what exactly was changed in that `react-table` update. The [release notes](https://github.com/patternfly/patternfly-react/releases?q=react-table&expanded=true) might be helpful. Otherwise, maybe we should do a bisect of that `[6, 39]` patch version range and see which particular version introduced the problem. If we can narrow that down we can try to prepare a separate small reproducer for the observed problem. If we can get it to happen again then we file a bug with PF, otherwise there is some other problem in our setup that should be fixable.

**Comment by tthvo** [comment]
https://github.com/patternfly/patternfly-react/pull/8521. seems to be pulling in `4.112.31`?

**Comment by tthvo** [comment]
I think this is the issue:

This line specifies that `SkipToContent` applies styles from button, button-primary, and skipToContent.

https://github.com/patternfly/patternfly-react/blob/25b70978ef1d779ff98260036ce83b94bff5c34e/packages/react-core/src/components/SkipToContent/SkipToContent.tsx#L37

But when rendering, notice how the `position: absolute` from skipToContent style is being override by `position: relative` from button.

![Screenshot from 2023-02-07 13-45-18](https://user-images.githubusercontent.com/68053619/217337461-1db1c766-d256-4bc1-9ecd-5b4845d082c3.png)

**Comment by tthvo** [comment]
Adding this line to `app.css` fixes it:

```css
.pf-c-skip-to-content {
  position: absolute !important;
}
```

I suspect exported @patternfly/react-core `base.css` order is incorrect.

**Comment by tthvo** [comment]
I tried creating a complete new application with same deps as cryostat-web: https://github.com/tthvo/sample-pf-react-app but could not reproduce the issue. Same for PF example with SkipToContent.

But I found out that the root problem seems to originates from code-splitting, which also split `*.css`. These css chunks can be applied in any order and unfortunately, it messes up the order. Not PF bug I think but our setup. So, the css fix seems reasonable now.

**Comment by andrewazores** [comment]
Ouch. Well, at least we don't need to bother the PF team.

But this does mean we could run into similar problems with css ordering due to splitting in the future. In this case the fix is small and seems low risk, but I imagine it could get a lot hairier in the future with other bugs in the same class.

So you're saying removing the splitting or css lazyload from the webpack config also resolves this particular issue? This seems to mean that what we're doing at the moment is trading correctness for performance. Maybe we need to back that out and be a little more conservative and what gets split and lazy loaded.

**Comment by tthvo** [comment]
>  Maybe we need to back that out and be a little more conservative and what gets split and lazy loaded.

Probably a problem with css splitting. Maybe we can back out css splitting and just bundle all css in a single chunk?

**Comment by andrewazores** [comment]
Would it be one giant css file that combines every css from the application and all deps? Or would it be "vendored" css files, roughly one from the application and one from each dep?

**Comment by tthvo** [comment]
>  Or would it be "vendored" css files, roughly one from the application and one from each dep?

hmm is this what happens now during build? I am bit unsure what the css orders are supposed to be in PF package so bundling all together cant seem to make sense...

**Comment by tthvo** [comment]
Actually, I just found out something even more interesting now that I look closer. Behaviour only happens if we visist route with table. That just means originally the order is correct. I am now suspecting a duplicate css bundle with incorrect order that comes with a lazy bundle...

**Comment by tthvo** [comment]
I dont know if we want to granularly fix these issues or find a way to control these css chunks. Maybe we need to completely back out lazy load route modules?

**Comment by andrewazores** [comment]
Nice, this is becoming a pretty clear picture of what's actually happening.

Let's save backing out the lazy loaded route modules for a last resort fix. It would be nice to keep that since it means application first load is more responsive and browser caching should be more effective. Maybe there are other strategies we can use to try to ensure that the css files have the right load order or right priority.

https://stackoverflow.com/questions/60632062/webpack-chunk-styles-and-react-lazy

https://stackoverflow.com/questions/64458711/using-react-lazy-in-cra-with-cssmodules-causes-chunks-to-have-duplicate-css-in-p

**Comment by tthvo** [comment]
Sure just opened it here: https://github.com/cryostatio/cryostat-web/pull/927
