### ISSUE TITLE
[Story] JVM details / JMX metrics Dashboard Card

### ISSUE THREAD

**Issue by maxcao13** [cryostatio/cryostat-web#865]
## Describe the feature
A Dashboard Card that contains JMX metric details and Cryostat JVM details. These include 
- [x] #894
- [x] #895
- [x] #874
- [x] #915

**Comment by andrewazores** [comment]
https://docs.oracle.com/javase/7/docs/jre/api/management/extension/com/sun/management/OperatingSystemMXBean.html

https://docs.oracle.com/javase/10/docs/api/java/lang/management/MemoryMXBean.html

https://docs.oracle.com/javase/8/docs/api/java/lang/management/RuntimeMXBean.html

https://docs.oracle.com/javase/8/docs/api/java/lang/management/ThreadMXBean.html

The backend side would simply be an API endpoint (and/or GraphQL fetcher) that clients can request various details from a target. Initially only over JMX but this could be expanded to over HTTP via the cryostat-agent in the future as well. By including HTTP query parameters or specifying fields in GraphQL, the client can request various details which get mapped by the server into remote requests to the target, and the returned values bundled up into an HTTP API JSON response to the client. I think the data would simply be pulled on demand and as a first pass with no particular caching strategy and no persistence.

**Comment by maxcao13** [comment]
Any other MBean attributes that could be added or should we close this now?

Still things like: 
```
bootClassPath
classPath
inputArguments
systemProperties
...
```
etc.

**Comment by andrewazores** [comment]
Any of those could be added too, though they will tend to be larger visually since these are lists of paths and things, so I think it'll be important to find ways to lay out the content nicely so it doesn't just feel like a wall of text.

**Comment by andrewazores** [comment]
#915
