### ISSUE TITLE
[Task] Set up Dashboard with default configuration for upgrading users

### ISSUE THREAD

**Issue by maxcao13** [cryostatio/cryostat-web#866]
Depends on #865 

## Describe the feature
A new user or user that has not upgraded to the new version 2.3.0 yet may not know about the new Dashboard features. We can detect whether this is true and have a default layout, and use cards that don't have too much computing power (JVM details, notes, etc.)

**Comment by tthvo** [comment]
I think maybe we can reuse the `_version` constant in Redux slicers for comparing?
