### ISSUE TITLE
[Story] Cryostat in-app guidance and tutorials

### ISSUE THREAD

**Issue by maxcao13** [cryostatio/cryostat-web#880]
Related #866 
## Describe the feature
Without the need to look at external documentation, we can have a good user experience within the app itself walking through some of the features that Cryostat offers, as well as having a quick tour of the application experience, similar to 

Openshift Console has a guided tour that maybe should be modeled similarly. We should also use [patternfly quickstarts](https://www.patternfly.org/v4/extensions/quick-starts/) for some in-app guides.

- [x] create guided tour of Cryostat
- [x] add various quickstarts
    - [x] Start/stop a recording
    - [x] Using settings page

**Comment by tthvo** [comment]
Very nice idea! I am thinking, a simpler version could be PF quick-starts: https://www.patternfly.org/v4/extensions/quick-starts

**Comment by tthvo** [comment]
On this note, we should make the quickstart drawer stays even when changing route so that the user can continue their quickstart steps while interacting with the UI. Right now, it onlys stays in `/quickstarts`.
