### ISSUE TITLE
[Question] AboutModal contains incorrect version of Cryostat

### ISSUE THREAD

**Issue by maxcao13** [cryostatio/cryostat-web#882]
## Current Behavior:
AboutModal contains a field `cryostatVersion` of 2.0.0-snapshot even though a development build of Cryostat should be of version `2.3.0-snapshot`. I'm unaware of what it says for newer production images of Cryostat.

## Expected Behavior:
The `HealthGetHandler` to return a correct, updated `cryostatVersion` field.

Is this something that should be fixed?

## Screenshots
![image](https://user-images.githubusercontent.com/69827283/218606950-9865a36d-06d3-4da4-bdc9-6ab5dcf4dd7d.png)

**Comment by andrewazores** [comment]
https://github.com/cryostatio/cryostat/blob/32870ff560342ebbc13862b97f304858470186a7/pom.xml#L407

Looks like this command invocation isn't returning the expected result. This gets output into a file at build time, which is packaged into the container image and what the health handler reads from for that response.

I think downstream product builds have a correct version but it would be nice for upstream images and dev images to have something a little more concise (ie referring to a more recent tag).

**Comment by ebaron** [comment]
Possibly related: https://github.com/cryostatio/cryostat/issues/966

**Comment by maxcao13** [comment]
I think this happens because the `main` branch of the cryostat repository is never tagged, and the production builds of cryostat are put into separate branches e.g. `cryostat-v2.2` and those branch commits are tagged. 

I assume if we tag the main branches commits at the certain relevant release breakpoints, then it would return a 'correct' response.

**Comment by andrewazores** [comment]
https://github.com/cryostatio/cryostat-web/pull/971#issuecomment-1517275364

This is done for 2.3.0 now and has been documented as part of the release checklist.
