### ISSUE TITLE
[Task] Remove explicit mention of JMX for Stored Credentials

### ISSUE THREAD

**Issue by andrewazores** [cryostatio/cryostat-web#900]
On that note though, the frontend needs to be updated to remove specific references to JMX, since these stored credentials will also be used for HTTP-based Agent connections.

_Originally posted by @andrewazores in https://github.com/cryostatio/cryostat/issues/1377#issuecomment-1448648881_

**Comment by tthvo** [comment]
Seems like this issue can be solved along with #914. What should I be writing here??
