### ISSUE TITLE
[Task] Reuse target details component in matchExpression views

### ISSUE THREAD

**Issue by andrewazores** [cryostatio/cryostat-web#912]
The right sidebar panel component here:

![image](https://user-images.githubusercontent.com/3787464/226461142-9f400187-b824-41a1-b1b0-f35c42739564.png)

represents the same information as the right side split component here:

![image](https://user-images.githubusercontent.com/3787464/226461223-05ba4672-f7dc-4d44-8f40-865fbf5de246.png)

This second old-style serialized JSON component is currently present on the `Automated Rules > Create` and `Security > Store JMX Credentials > Add` views. The new details component is much more pleasing to look at and probably makes it easier for the user to differentiate the different fields they're looking at. With some section renaming or tooltips, the field names required to build a matchExpression can be determined from the new details component pretty easily.

**Comment by tthvo** [comment]
> With some section renaming or tooltips, the field names required to build a matchExpression can be determined from the new details component pretty easily.

Are we putting the field name into the tooltip? 

Also, do we still need to keep the codeblock for hints? This is what I have right now:

![Screenshot from 2023-03-20 04-54-10](https://user-images.githubusercontent.com/68053619/226463316-c053ef8b-0fc9-4117-b73a-fea32161f7ca.png)

**Comment by andrewazores** [comment]
> Are we putting the field name into the tooltip?

I think so, maybe something like the JSON path, ex. `target.connectUrl` as the tooltip on "Connection URL". Or even just replace the "connection URL" section title with `target.connectUrl`.

> Also, do we still need to keep the codeblock for hints? This is what I have right now:

Not necessarily, though I think it's useful to provide a hint of some form somewhere. After #913 it's hopefully self-evident and easy enough that the hint block can be removed.

**Comment by tthvo** [comment]
Make sense thanks! I will add them in in the popover content.
