### ISSUE TITLE
[Task] "Create Recording" displays an unhelpful error view when performed on an HTTP Agent

### ISSUE THREAD

**Issue by andrewazores** [cryostatio/cryostat-web#944]
## Current Behavior:

"Recordings > Active > Create" results in an unhelpful error message and notification when the selected target is an HTTP-based Cryostat Agent.

## Expected Behavior:

Either there should be no error and the action should work as usual (TODO later on, this needs more consideration on the Agent side), or at least the error message should be more informative about why the action failed.

## Screenshots

![image](https://user-images.githubusercontent.com/3787464/231792963-d506cece-704b-417e-acac-8d28ff440d93.png)

**Comment by tthvo** [comment]
Just wondering how to trace this error message to a meaningful one? Or are we having like an special case for `http`-base target that returns a fixed custom message when any error happens?

**Comment by andrewazores** [comment]
The proper fix is to return a more useful error from the backend that has some informative error code (not 500), and ideally which also has some structured response body that the client can process.

In the timeframe we have for this release (ie. get done today), I think just handling it on the client side and displaying a specific error view if the target connection URL starts with `http` is good enough.

**Comment by andrewazores** [comment]
Since https://github.com/cryostatio/cryostat-agent/pull/175 and https://github.com/cryostatio/cryostat/pull/1608 , the situation is improved enough that I think this can be considered "done". Perhaps we just need to add some documentation about what HTTP 403 on an Agent target could mean with an error message like this (ie. turn on the `writes-enabled` config).

![image](https://github.com/cryostatio/cryostat-web/assets/3787464/039af531-161f-4c17-a9c5-c84b1e41d0ef)
