### ISSUE TITLE
[Story] Replace HTML-based Automated Analysis Report with JSON-backed component

### ISSUE THREAD

**Issue by andrewazores** [cryostatio/cryostat-web#949]
There are now two different visualizations for the Automated Analysis data. The original/legacy component that uses an HTML+JS+css document rendered into an `iframe` directly as produced by some JMC code via `cryostat-core`, and the new component visible on the Dashboard which uses the same JMC code to produce a JSON representation of the data and then renders this with Patternfly/React components.

The original component should be deleted from the codebase, since it has far fewer features than our new component (filtering, searching, etc.) and also has challenges around layout and applying styling (theming and accessibility).

We should also reconsider how to offer the Automated Analysis Report to the user. Now that this is available on the Dashboard, does it still make sense to expose it within the Recordings tables? If so, there must be a better way than hiding it in a collapsed table row.

**Comment by tthvo** [comment]
This is completed right?

**Comment by andrewazores** [comment]
Yes, I think so. There could be more work to do to further enhance the Dashboard version of the components or to bring more of those features to the recording table row embedded version, but that can/should be tracked separately.
